services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_gg
    environment:
      - 'POSTGRES_DB=nefrotrack'
      - 'POSTGRES_PASSWORD=nefrotrack'
      - 'POSTGRES_USER=nefrotrack'
    ports:
      - '5432:5432'
